stage1:
  path_to_ls_output: ./config/label_studio_output_example_stage_1.json
  path_to_images: /mnt/c/Users/cvres/Datasets/Meter
  height: 1028
  width: 1028
  path_to_output: ./output
  visualize: True
